
###
POST http://localhost:3000/api/dream/create HTTP/1.1
Content-Type: application/json

{
    "title" : "special",
    "description": "some dream i had",
    "date" : "04.9.1990",
    "type": "scary"
}

###
POST http://localhost:3000/api/dream/:id/update HTTP/1.1
Content-Type: application/json

{
    "title" : "special",
    "description": "some dream i had",
    "date" : "12.4.2021",
    "type": "sad"
}



###
DELETE http://localhost:3000/api/dream/:id/delete HTTP/1.1
Content-Type: application/json


###
GET http://localhost:3000/api/dream/all-dream-types HTTP/1.1


###
GET http://localhost:3000/api/dream/read HTTP/1.1


//// To filter between dates  ////

// Add an object with a name dateBetween, with props gt and lt, value shoud be a date

// "dateBetween" : {
//    "gt" : "04-04-1990",
//     "lt" : "02-04-2020"
// }
###
POST http://localhost:3000/api/dream/search?page=1&limit=2 HTTP/1.1
Content-Type: application/json

{
    "title":"special",
    "dateBetween" : {
        "gt" : "04-04-1990",
        "lt" : "02-04-2020"
    }
}
